### ISSUE TITLE
请问in.txt out.txt该放在哪里

### ISSUE THREAD

**Issue by mingyEx** [old-yan/CP-template#3]
按照readme里创建了如下项目结构：
![image](https://github.com/old-yan/CP-template/assets/40135358/d107d443-a4f0-4c73-9984-a041fa1d7fca)
但不知道该把输入输出文件放在哪里，[这里](https://github.com/old-yan/CP-template/blob/main/IO/FastIO.md#%E4%BA%8C%E6%A8%A1%E6%9D%BF%E5%8A%9F%E8%83%BD)说`本地调试的输入输出文件路径默认为执行目录下的 in.txt 和 out.txt。`

我尝试了直接放到生成的可执行文件所在的位置
![image](https://github.com/old-yan/CP-template/assets/40135358/d7612325-906d-49e3-a124-79a8f1480076)
但是依然看不到读取。

[这里](https://github.com/old-yan/CP-template/blob/main/README.md#3%E5%8A%9B%E6%89%A3%E8%BE%93%E5%85%A5%E8%BE%93%E5%87%BA%E6%A8%A1%E6%9D%BF%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)提到:    
1.在包含头文件之前，加一行 #define OY_LOCAL 作为本地的标志；（也可以在编译参数里加 -DOY_LOCAL）    
2.在运行目录下放入 in.txt 和 out.txt 作为输入输出文件；如果找不到运行目录，可以随便输出一个字符串，看看 out.txt 生成到了哪里。    
我在所有文件里第一行都添加了```#define _CRT_SECURE_NO_WARNINGS```，且在main.cpp里添加了 ```#define OY_LOCAL```
之后遇到了如下报错:
![image](https://github.com/old-yan/CP-template/assets/40135358/0309e6cb-749a-47d7-82da-34c4f30d571f)
若点击retry,则会定位到这里
![image](https://github.com/old-yan/CP-template/assets/40135358/6e1c2b46-0543-437d-ab00-4d3183624cfd)
调用栈和报错都在截图中。

自己写的本地调试辅助文件每次都得手动改输入类型，所以挺喜欢repo主的这个框架，但是`输入输出文件在哪行代码指定`这样的事，单看代码没法确定，且文件里有很多宏看不懂，只好求助。   
环境是
```
Windows 11 Pro Version	22H2 OS build	22621.2715   
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.7.6   
```

**Comment by mingyEx** [comment]
顺便一提，用cmake来组织文件结构似乎更好，可以针对不同的toolset生成文件结构，repo主是否有打算?
cmake支持从项目模板里直接把in/out文件复制到对应的地方，像[这样](https://github.com/mingyEx/leetcode-parser/blob/main/CMakeLists.txt#L18)

**Comment by old-yan** [comment]
1. 我看了一下我的 Visual Studio 项目，in.txt 和 out.txt 是位于和主文件同一目录下。 Visual Studio 的工作目录可能不是和 exe 所在的路径重合，所以可以在 cpp 所在的路径下创建 in.txt 和 out.txt 尝试一下；
2. fread 相关的错误，有可能是没有在正确的位置放置 in.txt 导致找不到输入文件而引发的错误。我试了一下把 in.txt 删掉，可以复现出你的错误；
3. 暂时没有 cmake 的计划。关于输入输出文件的问题，我在即将更新的版本中考虑使用宏生成输入输出文件地址，这样使用者可以通过项目的宏来控制输入输出文件地址，尽量提高使用者的使用自由度。

![image](https://github.com/old-yan/CP-template/assets/63179670/cc8506b9-f1a8-4fed-b10c-4388d721f540)

**Comment by old-yan** [comment]
在目前的版本里，已经可以通过编译时的宏来指定输入输出文件。

感谢您的反馈。

**Comment by mingyEx** [comment]
感谢回复，现在一切正常了。
我已经把自己惯用的[prettyprint](https://github.com/mingyEx/leetcode-parser/blob/main/leetcode/pprint.h)和来自[Aoxiang Cui](https://youtu.be/puFWxLalyGE?t=4317)的 [输出宏](https://github.com/mingyEx/leetcode-parser/blob/main/Solution.h#L33)加了进去,这样debug的时候输出东西比较方便：
![image](https://github.com/old-yan/CP-template/assets/40135358/16d1349d-fb18-409b-b3a7-867bbbe2cbab)

您的框架里是否有[打印可视化Tree](https://github.com/mingyEx/leetcode-parser/blob/main/leetcode/leetcode.h#L185)的东西，比如这样
![image](https://github.com/old-yan/CP-template/assets/40135358/a14167f1-1f32-41d1-b4c5-9d981dc07006)
如果没有的话要不要把我到处攒的代码加进去 >_<

**Comment by mingyEx** [comment]
合并代码的过程中`std::endl;`一直在报错..

**Comment by old-yan** [comment]
关于“万物打印器”和“树的展示”，我也有过一些想法，但是最终我还是没有去把相关的内容放到这个库里。

在我的设想中，这个库只提供一些最底层的通用工具，较为上层的一些可以二次开发的内容可以交给使用者自由制作。我注意到你提供的“pretty_print”里有对 set ， map ，  vector  等的输出重载，这个内容很多人也有自己的输出重载，我选择把这个重载留给使用者自己来补充。

关于树的打印和图的打印，在 [TREE](https://github.com/old-yan/CP-template/blob/main/TREE/LinkTree.h) 模板里，我标注了我用来观察树的形状的网站工具；观察图的网站并未在模板文件里给出，为 [https://csacademy.com/app/graph_editor/](https://csacademy.com/app/graph_editor/)  。我觉得这两个网站可以覆盖对通用的树、图打印的需求；力扣特有的树则在力扣进行可视化最佳。在找到一个比较完美的显示方案之前，暂不考虑控制台的输出。

**Comment by old-yan** [comment]
> 合并代码的过程中`std::endl;`一直在报错..

这是因为我的 FastIO.h 内将 `endl` 进行了宏定义，替换成了换行符 `\n` 。可以考虑把之后的 `std::endl` 修改为 `endl` ；或者在导入 FastIO.h 之后使用 ```#undef endl``` 把我的宏定义操作取消掉。

**Comment by mingyEx** [comment]
搞定了，把Tree.h和Tree.cpp都塞到了LeetcodeIO.h里。
顺便一问，一旦在*.h文件里放了函数定义，是不是就意味着该*.h文件不能被不同的*.cpp文件包含了，不然link期间必然会出错?

**Comment by old-yan** [comment]
> 搞定了，把Tree.h和Tree.cpp都塞到了LeetcodeIO.h里。 顺便一问，一旦在*.h文件里放了函数定义，是不是就意味着该*.h文件不能被不同的*.cpp文件包含了，不然link期间必然会出错?

不会啊，同一个头文件肯定可以被多个 cpp 文件包含，不然的话标准库头文件都不敢乱用了。如果你遇到的问题是符号重定义，可以按照我的头文件的宏的样式，使用宏来进行条件编译，这样对于同一个头文件只会编译一次，就可以避免符号重定义的问题。
