### ISSUE TITLE
AssignZkwTree 中 AssignMinZkw 的 modify 函数

### ISSUE THREAD

**Issue by bandiaoz** [old-yan/CP-template#4]
我希望实现区间推平，并询问区间最小值
```cpp
int main() {
    OY::AssignMinZkw<int> zkw(5, [&](int i) { return i; });
    std::cout << zkw << std::endl;
    zkw.modify(1, 3, 20);
    return 0;
}
```
该代码 `modify()` 函数报错，请问是什么原因，应该如何修改

**Comment by old-yan** [comment]
您好，经过检查是我的 `AssignZkwTree` 模板存在 `bug` 。

在 `modify` 函数实现上标记错了分支跳转，而在测试文件中只测试了 `AssignSumZkw` 而未对 `AssignMinZkw` 为首的另一类树做测试。现在已经把错误修复，并把 `AssignMinZkw` 添加到测试文件里，在下一次更新后就可以见到了。

如果你现在要用的话，可以把 `modify` 函数内的第 `218` 行修改如下：
```
if constexpr (!has_op || val_is_lazy || has_fast_pow)
```
非常感谢您的反馈！

**Comment by old-yan** [comment]
问题已修复。
